config/routes.rb
Rails.application.routes.draw do
  resources :events
  resource :sessions, only: [:new, :create, :destroy] #this is a singular resource, not resources.
  resources :users do
    resources :photos, only: [:index, :new, :create]
  end
  resources :photos
  root 'users#new'
   
  

  
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user

    has_attached_file :image, 
   :styles => {
      :original => ['1920x1680>', :jpg],
      :small    => ['100x100#',   :jpg],
      :medium   => ['250x250',    :jpg],
      :large    => ['500x500>',   :jpg]
    }
    validates_attachment_content_type :image, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  has_many :events
def to_s
  "This person's email is #{self.email}"
end
  has_secure_password
  has_many :photos  

   has_attached_file :photo, :styles => { 
    :medium => "300x300>", 
    :thumb => "100x100>",
    :icon => "50x50>" }, 
    :default_url => "/images/:style/missing.png"

   has_attached_file :avatar, :styles => { 
    :medium => "300x300>", 
    :thumb => "100x100>",
    :icon => "50x50>" }, 
    :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


  # TWO alternatives to validate presence of both handle and email:

    # validates :email, presence: true
    # validates :handle, presence: true

    #validates_presence_of :email, :handle

    #Now we want to have either handle or email, or both
    #But it can't have both email and handle blank


    #we can name our method whatever we chose, the def it.
    # validate :either_handle_or_email

    # def either_handle_or_email
    #   if (self.handle && self.handle.length > 0) || 
    #       (self.email && self.email.length > 0)
    #       return
    #   else
    #     self.errors.add(:email, "Must specify either handle or email")
    #     self.errors.add(:handle, "Must specify either handle or email")
    #   end
    # end

      # validates_format_of :email, with: /\A[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\z/

      # validates :email, {uniqueness: << true, message: "E-mail already in use!"}, {format: {with: /\A[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\z/}, message: "E-mail address should be in username@domain.com format"}

      # validates :email,   uniqueness: true
      # validates :email, {format: {with: /\A[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\z/}}

      # validates_format_of :password, with: /\A(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).{4,8}\z/, message: "Password expresion that requires one lower case letter, one upper case letter, one digit, 6-13 length, and no spaces."

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  helper_method :current_user 
  def current_user
     User.where(id:session["user_id"]).first
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @event = Event.all
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.first
  end

  def create
    
    event = current_user.events.new(event_params)
    invited = event.invited
      if event.save
        UserMailer.invite(invited).deliver_now
      redirect_to events_path
    else 
      redirect_to new_events_path
    end
  end

  def edit

  end

  def update
  end

  def destroy
  end

private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:event, :email, :title, :address, :invited, :date, :user_id)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end
  def new
    @photo =Photo.new
    if current_user == nil
      redirect_to new_sessions_path
    end
  end
  def create
    #Find our user that we should attach to. 
    if current_user != nil
      #this only works if a user is logged in. If no one is logged in it barfs.
      @photo = current_user.photos.new(photo_params)
      #or the standard create:
      #@photo = Photo.create(photo_params)
      if @photo.save
      redirect_to current_user
      else
      render 'new'
      end
    else
      redirect_to new_sessions_path
    end 
  end

  def show

  end

  def photo_params
    params.require(:photo).permit(:image, :photo_date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    
    # Find the user by email. The .where brings back a collection. The .first gives us the first one in that collection of users with that email. In the future, we'd set up our tables to accept only unique emails, so we'd not need the .first.
    u = User.where(email: params[:user][:email]).first
    if u !=nil && u.authenticate(params[:user][:password]) #this returns the object and is truthy, if correct password supplied
      session["user_id"] = u.id.to_s #converts user ID to a string. 
      redirect_to u #this is where we specify what we want a valid login to redirect to
    
    else
      redirect_to new_sessions_path
      end
  end

  def destroy
      session.destroy
      redirect_to new_sessions_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController #bitchezzzzz!!!!
  def index
    @users = User.all 
  end
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end
    
  def edit
    @user = User.find(params[:id])
    if current_user == nil
      redirect_to new_sessions_path
    end
    if current_user.id != @user.id
      redirect_to edit_user_path(current_user)
    end
  end

   def update
     user = User.find(params[:id])
    # respond_to do |format|
      if current_user.update(user_params) #could also use update_attributes method
        #format.html { redirect_to @user, notice: 'user was successfully updated.' }
        #format.json { render :show, status: :ok, location: @user }
        redirect_to user
      else
        #format.html { render :edit }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    # end
  end


  def create 
    
    user = User.new((params.require(:user).permit(:email, :first_name, :last_name)).merge(password:'12345'))
    
    #respond_to do |format|
      if user.save
        session["user_id"]=user.id.to_s
          UserMailer.welcome(user).deliver_now
          redirect_to edit_user_path(user)
        #format.html { redirect_to @user, notice: 'user was successfully created.' }
        #format.json { render :show, status: :created, location: @order }
      else
        redirect_to new_user_path
        #format.html { render :new }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    #end
  end



private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :bio_text, :avatar, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<section id="my-events" class="container">

	<h1>My Events</h1>

	<p>
		<% @event.each do |u| %>
		   <!-- Event User ID:<p><%#= u.user_id %></p> -->
		   <%= link_to u.title, event_path(u) %>

	</p>

	   

	<% end %>
</section

app/views/events/new.html.erb
<section id="events" class="container">
  <div class="dots col-md-12">
  <div class="col-md-4 col-md-offset-4 ms-formfield fill-in">


  <h1>Create An Event</h1>

   <%= bootstrap_form_for(@event) do |f| %>

        <div class="field">
          
          <%= f.date_field :date, placeholder: "Date" %>
        </div>

        <div class="field">
          <%= f.text_field :address, placeholder: "Address" %>
        </div>

        <div class="field">
          <%= f.text_field :title, placeholder: "Title" %>
        </div>

        <div class="field">
          <%= f.text_field :invited, placeholder: "Invited" %>
        </div>

        <div class="actions">
          <%= f.submit "Create An Event", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>

</section>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/_map.html.erb
<!-- Google Maps view -->
 <!DOCTYPE html>
<html>
  <head>

  <!-- seeing if this is getting ignored  

  Now is it? -->
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCnKu_jgX1HO78RP-td7d9uvup_TkmJg2k">
    </script>
    <script type="text/javascript">
      //function initialize() {
        //Plain View
        // var myLatlng = new google.maps.LatLng(-25.363882,131.044922);
        // var mapOptions = {
        //   center: { lat: 34.012982, lng: -118.495186},
        //   zoom: 20
        // };
        // var map = new google.maps.Map(document.getElementById('map-canvas'),
        //     mapOptions);

        // Marker view
        // var myLatlng = new google.maps.LatLng(34.012982,-118.495186);
        // var mapOptions = {
        //   zoom: 20,
        //   center: myLatlng
        // }
        // var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

        // // To add the marker to the map, use the 'map' property
        // var marker = new google.maps.Marker({
        // position: myLatlng,
        // map: map,
        // title:"General Assembly!"
        // });

        //Add marker directly

        // var myLatlng = new google.maps.LatLng(34.012982,-118.495186);
        // var mapOptions = {
        //   zoom: 20,
        //   center: myLatlng
        // }
        // var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

        // var marker = new google.maps.Marker({
        //     position: myLatlng,
        //     title:"General Assembly!"
        // });

        // // To add the marker to the map, call setMap();
        // marker.setMap(map);

      // }
      // google.maps.event.addDomListener(window, 'load', initialize);

      // Animate a marker
      // The following example creates a marker in SaMo, CA
      // using a DROP animation. Clicking on the marker will toggle
      // the animation between a BOUNCE animation and no animation.

      var saMo = new google.maps.LatLng(34.012982, -118.495186);
      var gA = new google.maps.LatLng(34.012982, -118.495186);
      var marker;
      var map;
      //var image = {url: 'https://generalassemb.ly/online/assets/ga-lockup-logo-9d95d5d0a1c966540edaedcb440b1963.png', size: new google.maps.Size(200, 302)}
      var infowindow = new google.maps.InfoWindow();
      var i = 0;

      function initialize() {
        var mapOptions = {
          zoom: 20,
          center: saMo
        };

        map = new google.maps.Map(document.getElementById('map-canvas'),
                mapOptions);

        marker = new google.maps.Marker({
          map:map,
          //draggable:true,
          //animation: google.maps.Animation.DROP,
          position: gA,
          title:"General Assembly!",
          //icon: image,


        });
        //google.maps.event.addListener(marker, 'click', toggleBounce);

        //this bit adds the info window
        google.maps.event.addListener(marker, 'click', (function(marker, i) {
               return function() {
                 infowindow.setContent("General Assembly!");
                 infowindow.open(map, marker);
               }
             })(marker, i));
      }
      //Animatin toggle
      // function toggleBounce() {

      //   if (marker.getAnimation() != null) {
      //     marker.setAnimation(null);
      //   } else {
      //     marker.setAnimation(google.maps.Animation.BOUNCE);
      //   }
      // }

      google.maps.event.addDomListener(window, 'load', initialize);





    </script>
  </head>
  <body>
<div id="map-canvas"></div>
  </body>
</html>

app/views/layouts/_nav.html.erb
 <nav class="navbar navbar-default navbar-inverse navbar-static-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">DataLus</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav pull-right">
        

        <!-- this is sloppy and the whole navbar and styling needs to be redone -->
          <% if current_user != nil %>
            <li class="active"> <%#= link_to "Home", show_user_path %></li>
            <li class="active"> <%= link_to "Create Event", new_event_path %> </li>
            <li class="active"> <%= link_to "My Profile", edit_user_path(current_user)%></li>
            <li class="active"> <%= link_to "My Events", events_path %> </li>
            <li class="active"> <%= link_to "Log out", sessions_path, method: :delete %></li>

           

          <% else %>
            <li class="active"> <%= link_to "Sign up", new_user_path, method: :get %></li>
            <li class="active"> <%= link_to "Log in", new_sessions_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </nav>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
<head>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/parallax/1.1.1/parallax.min.js"></script>
<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script> -->
<!-- <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"></link> -->
<!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">  -->
  <title>DataLus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/nav'%>

<%= yield %>

</body>
</html>

app/views/photos/new.html.erb
  <h1>Photos#new</h1>
    <p>Find me in app/views/photos/new.html.erb</p>

    <%= form_for(@photo) do |f| %>

      <div class="field">
        <%= f.label :photo_date %><br>
        <%= f.date_field :photo_date %>
      </div>

      <div class="field">
        <%= f.label :image %><br>
        <%= f.file_field :image %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>

app/views/users/edit.html.erb
<section id="blank-bg" class="container">
  <div class="dots col-md-12">
    <div id="welcome"></div>
  <div class="col-md-4 col-md-offset-4 ms-formfield fill-in">
    <h1>User Profile</h1>
    <%= bootstrap_form_for(@user) do |f| %>
    <%= f.text_field :email, hide_label: true,  placeholder: "e-mail" %>
    <%= f.password_field :password, hide_label: true, placeholder: "Password"  %>
    <%#= f.password_field :password_confirmation, hide_label: true, placeholder: "Password Confirmation" %>
    <%= f.text_field :first_name, hide_label: true, placeholder: "Full Name"  %>
    <%#= f.text_field :last_name, hide_label: true, placeholder: "Last Name"  %>
    <%#= f.text_field :bio_text,  hide_label: true,placeholder: "About you!" %>
    <%#= f.file_field :avatar, hide_label: true, placeholder: "Profile Picture", :class => "btn btn-default btn-primary" %>
    <%= f.primary "Create User" %>
<!-- Trigger email sent for new user -->
  </div>
  <% end %>
   <!-- </div> -->
</div>
</div>

</section>

app/views/users/index.html.erb
<div class="container-fluid">
<br />
<br />
<br />
<% @users.each do |u| %>*
    <%= u.email %>
<% end %>
</div>

app/views/users/new.html.erb
<section id="home" class="row-fluid">
      <div class="dots">
          <div id="welcome"></div>
            <%= image_tag("data-logo.png", :alt => "rss feed", :class => 'data-logo') %>


    <div class="col-md-4 col-md-offset-4 ms-formfield">
      <%= bootstrap_form_for(@user) do |f| %><br />
      <%= f.text_field :email, hide_label: true,  placeholder: "Email"%>
      <%= f.text_field :first_name, hide_label: true, placeholder: "Full Name"%>
      <%= f.text_field :last_name, hide_label: true, placeholder: "Last Name"%>
      <%= f.primary "Join Event" %>
      <!-- Trigger email sent for new user -->

      <% end %>
    </div>
      </div>

</section>

app/views/users/show.html.erb
<section id="adventure-bg" class="container">

    <div class="row-fluid">
     
        <h1></h1>

        <div class="user-profile">
            <%=image_tag("greg-w.png", :class => 'greg-w')%>
            <h2><%= @user.first_name %><%= @user.last_name %><br /></h2>
            <%= @user.bio_text %><br />
            <%= image_tag @user.avatar.url(:thumb) %>
<!--             <p class="email-user"><%#= @user.email %><br /></p>
 -->

    <%#= link_to "Upload photo", new_user_photo_path(@user) %>

                <% @user.photos.each do |p| %>
                    <%#= image_tag p.image.url(:medium) %>
              
                <% end %>
          </div>
               
          

    </div>
</section>
  

      
  